package com.example.mobile.shared.constants

object MedicalSpecializations {
    val ALL = listOf(
        "Allergy and Immunology",
        "Anesthesiology",
        "Cardiology",
        "Cardiovascular Surgery",
        "Clinical Pharmacology",
        "Dermatology",
        "Diagnostic Radiology",
        "Emergency Medicine",
        "Endocrinology",
        "Family Medicine",
        "Forensic Medicine",
        "Gastroenterology",
        "General Practice",
        "General Surgery",
        "Geriatrics",
        "Hematology",
        "Infectious Disease",
        "Internal Medicine",
        "Interventional Radiology",
        "Neonatology",
        "Nephrology",
        "Neurology",
        "Neurosurgery",
        "Nuclear Medicine",
        "Obstetrics and Gynecology",
        "Occupational Medicine",
        "Oncology",
        "Ophthalmology",
        "Orthopedics",
        "Otolaryngology (ENT)",
        "Pain Medicine",
        "Palliative Medicine",
        "Pathology",
        "Pediatrics",
        "Physical Medicine and Rehabilitation",
        "Plastic Surgery",
        "Preventive Medicine",
        "Psychiatry",
        "Pulmonology",
        "Radiation Oncology",
        "Radiology",
        "Rheumatology",
        "Sports Medicine",
        "Thoracic Surgery",
        "Toxicology",
        "Urology",
        "Vascular Surgery",
    )
}