/**
 * Comprehensive list of medical specializations.
 * Used in doctor registration, profile editing, and patient search filters.
 */
const MEDICAL_SPECIALIZATIONS = [
  'Allergy and Immunology',
  'Anesthesiology',
  'Cardiology',
  'Cardiovascular Surgery',
  'Clinical Pharmacology',
  'Dermatology',
  'Diagnostic Radiology',
  'Emergency Medicine',
  'Endocrinology',
  'Family Medicine',
  'Forensic Medicine',
  'Gastroenterology',
  'General Practice',
  'General Surgery',
  'Geriatrics',
  'Hematology',
  'Infectious Disease',
  'Internal Medicine',
  'Interventional Radiology',
  'Neonatology',
  'Nephrology',
  'Neurology',
  'Neurosurgery',
  'Nuclear Medicine',
  'Obstetrics and Gynecology',
  'Occupational Medicine',
  'Oncology',
  'Ophthalmology',
  'Orthopedics',
  'Otolaryngology (ENT)',
  'Pain Medicine',
  'Palliative Medicine',
  'Pathology',
  'Pediatrics',
  'Physical Medicine and Rehabilitation',
  'Plastic Surgery',
  'Preventive Medicine',
  'Psychiatry',
  'Pulmonology',
  'Radiation Oncology',
  'Radiology',
  'Rheumatology',
  'Sports Medicine',
  'Thoracic Surgery',
  'Toxicology',
  'Urology',
  'Vascular Surgery',
];

export default MEDICAL_SPECIALIZATIONS;
